### DISCUSSION TITLE
Can't get Linkstack docker working with Traefik (HTTP ERROR 418)

### DISCUSSION THREAD

**Discussion by cb3inco** [JulianPrieber/llc-docker#128] [Issues]
I'm bewildered that I can't get Linkstack (docker) with Traefik. Site doesn't load, nothing works when I access the domain. All I get is HTTP ERROR 418.

```
services:
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack-app
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      - TZ=Europe/Berlin
      - SERVER_ADMIN=linkstackadmin@domain.com.com
      - HTTP_SERVER_NAME=domain.com
      - HTTPS_SERVER_NAME=domain.com
      - LOG_LEVEL=info
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=16M
    expose:
      - 80
      - 443
    volumes:
      - ./linkstack:/htdocs:rw
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "diun.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.linkstack.rule=Host(`domain.com`)"
      - "traefik.http.routers.linkstack.entrypoints=https"
      - "traefik.http.routers.linkstack.tls.certResolver=letls"
      - "traefik.http.services.linkstack.loadBalancer.server.port=443"
      - "traefik.http.services.linkstack.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.linkstack-head.headers.customrequestheaders.X-Forwarded-Proto=https"
#      - "traefik.http.middlewares.linkstack-head.headers.customResponseHeaders.X-Robots-Tag=none"
#      - "traefik.http.middlewares.linkstack-head.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
#      - "traefik.http.middlewares.linkstack-head.headers.stsSeconds=31536000"
#      - "traefik.http.middlewares.linkstack-head.headers.accesscontrolalloworiginlist=*"
volumes:
  linkstack:
networks:
  traefik:
    external: true
    name: traefik

```

I've tried various fixes (commenting, uncommenting, downloading the .zip file and copying the files into the volume, etc.)

My domain is proxied through Cloudflare and my host is IPv6 only. 

I've done enough setups with Traefik and none of this makes sense. What am I doing wrong?

When I review logs for the container it reads as such:

```
cat: can't open '/htdocs/version.json': No such file or directory
+ ------------------------------------------------------------------ +
|                      LINKSTACK v                           |
+ ------------------------------------------------------------------ +
| Updating Configuration: Apache Base (/etc/apache2/httpd.conf)      |
| Updating Configuration: Apache SSL  (/etc/apache2/conf.d/ssl.conf) |
| Updating Configuration: PHP         (/etc/php82/php.ini)            |
| Updating Configuration: Complete                                   |
| ------------------------------------------------------------------ |
| Running Apache                                                     |
+ ------------------------------------------------------------------ +

[Sat Jan 11 10:45:26.134106 2025] [ssl:info] [pid 34] AH01883: Init: Initialized OpenSSL library
[Sat Jan 11 10:45:26.136224 2025] [ssl:debug] [pid 34] ssl_engine_init.c(353): AH01886: OpenSSL has FIPS mode disabled
[Sat Jan 11 10:45:26.136257 2025] [ssl:info] [pid 34] AH01887: Init: Initializing (virtual) servers for SSL
[Sat Jan 11 10:45:26.138223 2025] [ssl:info] [pid 34] AH01876: mod_ssl/2.4.57 compiled against Server: Apache/2.4.57, Library: OpenSSL/3.1.0
[Sat Jan 11 10:45:26.152186 2025] [ssl:info] [pid 34] AH01883: Init: Initialized OpenSSL library
[Sat Jan 11 10:45:26.152231 2025] [ssl:debug] [pid 34] ssl_engine_init.c(353): AH01886: OpenSSL has FIPS mode disabled
[Sat Jan 11 10:45:26.152258 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(414): AH00821: shmcb_init allocated 512000 bytes of shared memory
[Sat Jan 11 10:45:26.152261 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(428): AH00822: for 511912 bytes (512000 including header), recommending 32 subcaches, 88 indexes each
[Sat Jan 11 10:45:26.152263 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(465): AH00824: shmcb_init_memory choices follow
[Sat Jan 11 10:45:26.152265 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(467): AH00825: subcache_num = 32
[Sat Jan 11 10:45:26.152266 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(469): AH00826: subcache_size = 15992
[Sat Jan 11 10:45:26.152269 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(471): AH00827: subcache_data_offset = 2128
[Sat Jan 11 10:45:26.152271 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(473): AH00828: subcache_data_size = 13864
[Sat Jan 11 10:45:26.152273 2025] [socache_shmcb:debug] [pid 34] mod_socache_shmcb.c(475): AH00829: index_num = 88
[Sat Jan 11 10:45:26.152334 2025] [socache_shmcb:info] [pid 34] AH00830: Shared memory socache initialised
[Sat Jan 11 10:45:26.152344 2025] [ssl:info] [pid 34] AH01887: Init: Initializing (virtual) servers for SSL
[Sat Jan 11 10:45:26.153569 2025] [ssl:info] [pid 34] AH01876: mod_ssl/2.4.57 compiled against Server: Apache/2.4.57, Library: OpenSSL/3.1.0
[Sat Jan 11 10:45:26.157014 2025] [mpm_prefork:notice] [pid 34] AH00163: Apache/2.4.57 (Unix) PHP/8.2.7 OpenSSL/3.1.1 configured -- resuming normal operations
[Sat Jan 11 10:45:26.157031 2025] [mpm_prefork:info] [pid 34] AH00164: Server built: Apr 28 2023 21:13:09
[Sat Jan 11 10:45:26.157049 2025] [core:notice] [pid 34] AH00094: Command line: 'httpd -D FOREGROUND'
[Sat Jan 11 10:45:26.157052 2025] [core:debug] [pid 34] log.c(1570): AH02639: Using SO_REUSEPORT: yes (1)
[Sat Jan 11 10:45:26.157054 2025] [mpm_prefork:debug] [pid 34] prefork.c(970): AH00165: Accept mutex: pthread (default: pthread)
[Sat Jan 11 10:45:56.099500 2025] [authz_core:debug] [pid 35] mod_authz_core.c(815): [client 127.0.0.1:47142] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:45:56.099526 2025] [authz_core:debug] [pid 35] mod_authz_core.c(815): [client 127.0.0.1:47142] AH01626: authorization result of <RequireAny>: granted
[Sat Jan 11 10:45:56.099576 2025] [authz_core:debug] [pid 35] mod_authz_core.c(815): [client 127.0.0.1:47142] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:45:56.099583 2025] [authz_core:debug] [pid 35] mod_authz_core.c(815): [client 127.0.0.1:47142] AH01626: authorization result of <RequireAny>: granted
[Sat Jan 11 10:46:26.159505 2025] [authz_core:debug] [pid 36] mod_authz_core.c(815): [client 127.0.0.1:48722] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:46:26.159532 2025] [authz_core:debug] [pid 36] mod_authz_core.c(815): [client 127.0.0.1:48722] AH01626: authorization result of <RequireAny>: granted
[Sat Jan 11 10:46:26.159582 2025] [authz_core:debug] [pid 36] mod_authz_core.c(815): [client 127.0.0.1:48722] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:46:26.159585 2025] [authz_core:debug] [pid 36] mod_authz_core.c(815): [client 127.0.0.1:48722] AH01626: authorization result of <RequireAny>: granted
[Sat Jan 11 10:46:56.200607 2025] [authz_core:debug] [pid 37] mod_authz_core.c(815): [client 127.0.0.1:36816] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:46:56.200632 2025] [authz_core:debug] [pid 37] mod_authz_core.c(815): [client 127.0.0.1:36816] AH01626: authorization result of <RequireAny>: granted
[Sat Jan 11 10:46:56.200703 2025] [authz_core:debug] [pid 37] mod_authz_core.c(815): [client 127.0.0.1:36816] AH01626: authorization result of Require all granted: granted
[Sat Jan 11 10:46:56.200710 2025] [authz_core:debug] [pid 37] mod_authz_core.c(815): [client 127.0.0.1:36816] AH01626: authorization result of <RequireAny>: granted
```

**Comment by lastsamurai26** [comment]
create a new file as dyn conf 
with this content 
```
http:
  serversTransports:
    noverifing:
      insecureSkipVerify: true
```
and add this as label 
`      - "traefik.http.services.linkstack.loadBalancer.serversTransport=noverifing@file"`




this are my labels -> and it works 

```
      - "traefik.enable=true"
      - "traefik.http.routers.linkstack.entrypoints=websecure"
      - "traefik.http.routers.linkstack.rule=Host(`domain.dev`)"
      - "traefik.http.routers.linkstack.tls=true"
      - "traefik.http.routers.linkstack.tls.certresolver=http_resolver"
      - "traefik.http.routers.linkstack.service=linkstack"
      - "traefik.http.services.linkstack.loadbalancer.server.port=443"
      - "traefik.http.services.linkstack.loadbalancer.server.scheme=https"
      - "traefik.http.services.linkstack.loadBalancer.serversTransport=noverifing@file"

      - "traefik.docker.network=proxy"
      - "traefik.http.routers.linkstack.middlewares=linkstack-head"
      - "traefik.http.middlewares.linkstack-head.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.linkstack-head.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.linkstack-head.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
      - "traefik.http.middlewares.linkstack-head.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.linkstack-head.headers.accesscontrolalloworiginlist=*"
```
