### ISSUE TITLE
How to setup with a reverse proxy?

### ISSUE THREAD

**Issue by LeoColman** [JulianPrieber/llc-docker#7]
I'm trying to use this docker-compose to deploy the docker image:

```
version: "3.8"

services:
  littlelink-custom:
    image: julianprieber/littlelink-custom
    networks:
      - caddy
    labels:
      caddy: littlelink.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
```

However, it's not working. I think littlelink is trying to do HTTP stuff even when it should do HTTPS stuff.

The website looks like this:

![image](https://user-images.githubusercontent.com/1577251/184226275-fb2a4573-66b5-4eed-abbf-4ef08027050e.png)

It won't load because mixing http and https is not allowed:

![image](https://user-images.githubusercontent.com/1577251/184226408-8fbb8f09-40c9-40b3-9a9f-a859689a9506.png)

----

How can I handle SSL termination outside little-link?

**Comment by JulianPrieber** [comment]
I need more information on your setup.

You appear to be using Apache for your reverse proxy. If that's the case, I'd recommend using the web version of LittleLink Custom for better performance. https://github.com/JulianPrieber/littlelink-custom

Otherwise, I would need more information about what you're trying to do.

Can you access your Docker Container locally on whatever port you deployed it on?

**Comment by LeoColman** [comment]
I'm trying to launch it via docker, and proxy to it via Caddy.

Caddy is a tool similar to nginx - https://caddyserver.com/

I'm specifically using https://github.com/lucaslorentz/caddy-docker-proxy to use it in docker. It's a reverse proxy.

How can I launch the web version using docker? I thought this was the repository for it

**Comment by JulianPrieber** [comment]
The docker version is launching the web version, just in a docker. For the web version, you'd just need a web server.

I added an example for a NGINX reverse proxy config to the readme.md https://github.com/JulianPrieber/llc-docker#8
I hope you can work with that.

**Comment by LeoColman** [comment]
Yes!
This bit helped:

```
# Fixes Mixed Content errors.
add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
```
So I had to change my setup to:

```
version: "3.8"

services:
  littlelink-custom:
    image: julianprieber/littlelink-custom
    networks:
      - caddy
    labels:
      caddy: littlelink.semudando.com.br
      caddy.header.Content-Security-Policy: "upgrade-insecure-requests"
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
```

The only difference beeing adding the upgrade insecure requests header.
